# Generated by Django 5.1.7 on 2026-03-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=200)),
                ('ctc', models.DecimalField(decimal_places=2, help_text='CTC in LPA', max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Both', 'Both')], default='Full-Time', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('OTHER', 'Other')], default='CSE', max_length=10)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('passing_year', models.IntegerField()),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('internship_done', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.DecimalField(decimal_places=2, help_text='Package in LPA', max_digits=10)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Not Placed', 'Not Placed'), ('In Progress', 'In Progress')], default='In Progress', max_length=20)),
                ('placement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement_app.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
