# Generated by Django 4.2.29 on 2026-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='offer_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Both', 'Both')], db_index=True, default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Not Placed', 'Not Placed'), ('In Progress', 'In Progress')], db_index=True, default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('OTHER', 'Other')], db_index=True, default='CSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year',
            field=models.IntegerField(db_index=True),
        ),
    ]
